// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomType struct {
	CustomInput          string   `protobuf:"bytes,1,opt,name=custom_input,json=customInput,proto3" json:"custom_input,omitempty"`
	CustomBool           bool     `protobuf:"varint,2,opt,name=custom_bool,json=customBool,proto3" json:"custom_bool,omitempty"`
	CustomInt            int32    `protobuf:"varint,3,opt,name=custom_int,json=customInt,proto3" json:"custom_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomType) Reset()         { *m = CustomType{} }
func (m *CustomType) String() string { return proto.CompactTextString(m) }
func (*CustomType) ProtoMessage()    {}
func (*CustomType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *CustomType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomType.Unmarshal(m, b)
}
func (m *CustomType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomType.Marshal(b, m, deterministic)
}
func (m *CustomType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomType.Merge(m, src)
}
func (m *CustomType) XXX_Size() int {
	return xxx_messageInfo_CustomType.Size(m)
}
func (m *CustomType) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomType.DiscardUnknown(m)
}

var xxx_messageInfo_CustomType proto.InternalMessageInfo

func (m *CustomType) GetCustomInput() string {
	if m != nil {
		return m.CustomInput
	}
	return ""
}

func (m *CustomType) GetCustomBool() bool {
	if m != nil {
		return m.CustomBool
	}
	return false
}

func (m *CustomType) GetCustomInt() int32 {
	if m != nil {
		return m.CustomInt
	}
	return 0
}

var E_Tags = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         999999,
	Name:          "tags",
	Tag:           "bytes,999999,opt,name=tags",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*CustomType)(nil), "CustomType")
	proto.RegisterExtension(E_Tags)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0xf2, 0x8b,
	0x20, 0x2a, 0x94, 0xf2, 0xb9, 0xb8, 0x9c, 0x4b, 0x8b, 0x4b, 0xf2, 0x73, 0x43, 0x2a, 0x0b, 0x52,
	0x85, 0x14, 0xb9, 0x78, 0x92, 0xc1, 0xbc, 0xf8, 0xcc, 0xbc, 0x82, 0xd2, 0x12, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x6e, 0x88, 0x98, 0x27, 0x48, 0x48, 0x48, 0x9e, 0x0b, 0xca, 0x8d, 0x4f,
	0xca, 0xcf, 0xcf, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x08, 0xe2, 0x82, 0x08, 0x39, 0xe5, 0xe7,
	0xe7, 0x08, 0xc9, 0x72, 0x71, 0xc1, 0xcd, 0x28, 0x91, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0xe2,
	0x84, 0x99, 0x50, 0x62, 0x65, 0xcc, 0xc5, 0x52, 0x92, 0x98, 0x5e, 0x2c, 0x24, 0xab, 0x07, 0x71,
	0x9b, 0x1e, 0xcc, 0x6d, 0x7a, 0x6e, 0x99, 0xa9, 0x39, 0x29, 0xfe, 0x05, 0x25, 0x99, 0xf9, 0x79,
	0xc5, 0x12, 0xfb, 0x5b, 0x6c, 0xc1, 0x76, 0x83, 0x15, 0x3b, 0xb1, 0x44, 0x31, 0x15, 0x24, 0x25,
	0xb1, 0x81, 0x95, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xfc, 0xc8, 0x2d, 0xe3, 0x00,
	0x00, 0x00,
}
